import {
  FiUsers, FiHome, FiTrendingUp, FiTarget, FiDollarSign,
  FiAlertCircle, FiBook, FiSend, FiPackage, FiFileText,
  FiClipboard, FiShoppingCart, FiUserCheck, FiBriefcase,
  FiCheckSquare, FiCalendar, FiMap, FiShield, FiFlag,
  FiCpu, FiLayers, FiStar, FiClock, FiTool,
  FiActivity, FiMail, FiCreditCard, FiDollarSign as FiPayment,
  FiTruck, FiTag, FiPercent, FiEye, FiBell,
  FiPieChart, FiAward, FiFileText as FiContract, FiBarChart2
} from 'react-icons/fi';

export const modules = {
  contacts: {
    key: 'contacts',
    name: 'Contacts',
    icon: FiUsers,
    color: '#0078D4',
    description: 'Manage customer contacts and relationships',
    columns: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'email', label: 'Email' },
      { key: 'company', label: 'Company' },
      { key: 'phone', label: 'Phone' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'first_name', label: 'First Name', type: 'text', required: true },
      { key: 'last_name', label: 'Last Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'job_title', label: 'Job Title', type: 'text' },
      { key: 'address', label: 'Address', type: 'text' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  accounts: {
    key: 'accounts',
    name: 'Accounts',
    icon: FiHome,
    color: '#107C10',
    description: 'Manage business accounts and organizations',
    columns: [
      { key: 'name', label: 'Account Name' },
      { key: 'industry', label: 'Industry' },
      { key: 'phone', label: 'Phone' },
      { key: 'annual_revenue', label: 'Revenue', format: 'currency' },
      { key: 'employee_count', label: 'Employees' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Account Name', type: 'text', required: true },
      { key: 'industry', label: 'Industry', type: 'select', options: ['Technology', 'Software', 'Financial Services', 'Healthcare', 'Retail', 'Education', 'Energy', 'Aerospace', 'Cybersecurity', 'Media', 'Logistics', 'Analytics', 'Cloud Computing'] },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'address', label: 'Address', type: 'text' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'annual_revenue', label: 'Annual Revenue', type: 'number' },
      { key: 'employee_count', label: 'Employee Count', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: ['Enterprise', 'Mid-Market', 'SMB'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  leads: {
    key: 'leads',
    name: 'Leads',
    icon: FiTrendingUp,
    color: '#FF8C00',
    description: 'Track and manage sales leads',
    columns: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'company', label: 'Company' },
      { key: 'source', label: 'Source' },
      { key: 'rating', label: 'Rating', badge: true },
      { key: 'estimated_value', label: 'Est. Value', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'first_name', label: 'First Name', type: 'text', required: true },
      { key: 'last_name', label: 'Last Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'job_title', label: 'Job Title', type: 'text' },
      { key: 'source', label: 'Source', type: 'select', options: ['Website', 'Referral', 'LinkedIn', 'Trade Show', 'Cold Call', 'Event', 'Partner'] },
      { key: 'status', label: 'Status', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Disqualified'] },
      { key: 'rating', label: 'Rating', type: 'select', options: ['Hot', 'Warm', 'Cold'] },
      { key: 'estimated_value', label: 'Estimated Value', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  opportunities: {
    key: 'opportunities',
    name: 'Opportunities',
    icon: FiTarget,
    color: '#E74856',
    description: 'Manage sales opportunities and deals',
    columns: [
      { key: 'name', label: 'Opportunity' },
      { key: 'account_name', label: 'Account' },
      { key: 'amount', label: 'Amount', format: 'currency' },
      { key: 'stage', label: 'Stage', badge: true },
      { key: 'probability', label: 'Probability', format: 'percent' },
      { key: 'close_date', label: 'Close Date', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Opportunity Name', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'stage', label: 'Stage', type: 'select', options: ['Qualify', 'Develop', 'Propose', 'Negotiate', 'Close'] },
      { key: 'probability', label: 'Probability (%)', type: 'number' },
      { key: 'close_date', label: 'Close Date', type: 'date' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Open', 'Won', 'Lost'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  cases: {
    key: 'cases',
    name: 'Cases',
    icon: FiAlertCircle,
    color: '#D83B01',
    description: 'Customer service cases and support tickets',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'contact_name', label: 'Contact' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'status', label: 'Status', badge: true },
      { key: 'category', label: 'Category' },
      { key: 'assigned_to', label: 'Assigned To' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['New', 'In Progress', 'Waiting', 'Resolved', 'Closed'] },
      { key: 'category', label: 'Category', type: 'select', options: ['Technical', 'Billing', 'Feature Request', 'Bug', 'Support', 'Compliance', 'Training', 'Licensing'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'resolution', label: 'Resolution', type: 'textarea' },
      { key: 'assigned_to', label: 'Assigned To', type: 'text' },
    ],
  },
  knowledge_articles: {
    key: 'knowledge_articles',
    name: 'Knowledge Base',
    icon: FiBook,
    color: '#8764B8',
    description: 'Knowledge articles and documentation',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'category', label: 'Category' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'author', label: 'Author' },
      { key: 'views', label: 'Views' },
      { key: 'helpful_votes', label: 'Helpful' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['Getting Started', 'Configuration', 'Customization', 'Development', 'Automation', 'Administration', 'Data Management', 'Troubleshooting', 'Mobile', 'Reporting', 'Integration', 'Sales', 'Customer Service', 'Tips & Tricks'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Published', 'Archived'] },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'text' },
    ],
  },
  campaigns: {
    key: 'campaigns',
    name: 'Campaigns',
    icon: FiSend,
    color: '#00B7C3',
    description: 'Marketing campaigns and initiatives',
    columns: [
      { key: 'name', label: 'Campaign' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'budget', label: 'Budget', format: 'currency' },
      { key: 'channel', label: 'Channel' },
      { key: 'start_date', label: 'Start', format: 'date' },
    ],
    fields: [
      { key: 'name', label: 'Campaign Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Product Launch', 'Webinar', 'Partner', 'Event', 'Advertising', 'Content', 'Industry', 'Social Media', 'Email', 'Community', 'Referral'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Planning', 'Active', 'Completed', 'Cancelled'] },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'budget', label: 'Budget', type: 'number' },
      { key: 'actual_cost', label: 'Actual Cost', type: 'number' },
      { key: 'expected_revenue', label: 'Expected Revenue', type: 'number' },
      { key: 'target_audience', label: 'Target Audience', type: 'text' },
      { key: 'channel', label: 'Channel', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  products: {
    key: 'products',
    name: 'Products',
    icon: FiPackage,
    color: '#498205',
    description: 'Product catalog and pricing',
    columns: [
      { key: 'name', label: 'Product' },
      { key: 'sku', label: 'SKU' },
      { key: 'category', label: 'Category' },
      { key: 'price', label: 'Price', format: 'currency' },
      { key: 'quantity_in_stock', label: 'Stock' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Product Name', type: 'text', required: true },
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['CRM', 'ERP', 'Service', 'Marketing', 'HR', 'Projects', 'Analytics', 'Automation', 'Commerce', 'AI', 'Storage', 'Support'] },
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'cost', label: 'Cost', type: 'number' },
      { key: 'quantity_in_stock', label: 'Quantity in Stock', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Discontinued'] },
      { key: 'vendor', label: 'Vendor', type: 'text' },
    ],
  },
  invoices: {
    key: 'invoices',
    name: 'Invoices',
    icon: FiFileText,
    color: '#005A9E',
    description: 'Manage invoices and billing',
    columns: [
      { key: 'invoice_number', label: 'Invoice #' },
      { key: 'account_name', label: 'Account' },
      { key: 'total', label: 'Total', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'due_date', label: 'Due Date', format: 'date' },
    ],
    fields: [
      { key: 'invoice_number', label: 'Invoice Number', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'tax', label: 'Tax', type: 'number' },
      { key: 'total', label: 'Total', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Pending', 'Paid', 'Overdue', 'Cancelled'] },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'paid_date', label: 'Paid Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  quotes: {
    key: 'quotes',
    name: 'Quotes',
    icon: FiClipboard,
    color: '#7719AA',
    description: 'Sales quotes and proposals',
    columns: [
      { key: 'quote_number', label: 'Quote #' },
      { key: 'name', label: 'Name' },
      { key: 'account_name', label: 'Account' },
      { key: 'total', label: 'Total', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'valid_until', label: 'Valid Until', format: 'date' },
    ],
    fields: [
      { key: 'quote_number', label: 'Quote Number', type: 'text', required: true },
      { key: 'name', label: 'Quote Name', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'discount', label: 'Discount (%)', type: 'number' },
      { key: 'total', label: 'Total', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Won', 'Lost', 'Expired'] },
      { key: 'valid_until', label: 'Valid Until', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  orders: {
    key: 'orders',
    name: 'Orders',
    icon: FiShoppingCart,
    color: '#C239B3',
    description: 'Sales orders and fulfillment',
    columns: [
      { key: 'order_number', label: 'Order #' },
      { key: 'account_name', label: 'Account' },
      { key: 'total', label: 'Total', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'order_date', label: 'Order Date', format: 'date' },
    ],
    fields: [
      { key: 'order_number', label: 'Order Number', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number' },
      { key: 'tax', label: 'Tax', type: 'number' },
      { key: 'total', label: 'Total', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled'] },
      { key: 'shipping_address', label: 'Shipping Address', type: 'textarea' },
      { key: 'order_date', label: 'Order Date', type: 'date' },
      { key: 'ship_date', label: 'Ship Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  employees: {
    key: 'employees',
    name: 'Employees',
    icon: FiUserCheck,
    color: '#E3008C',
    description: 'Human resources and employee management',
    columns: [
      { key: 'first_name', label: 'First Name' },
      { key: 'last_name', label: 'Last Name' },
      { key: 'department', label: 'Department' },
      { key: 'position', label: 'Position' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'first_name', label: 'First Name', type: 'text', required: true },
      { key: 'last_name', label: 'Last Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'department', label: 'Department', type: 'select', options: ['Engineering', 'Sales', 'Marketing', 'Customer Service', 'Finance', 'HR'] },
      { key: 'position', label: 'Position', type: 'text' },
      { key: 'manager', label: 'Manager', type: 'text' },
      { key: 'hire_date', label: 'Hire Date', type: 'date' },
      { key: 'salary', label: 'Salary', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'On Leave', 'Terminated'] },
      { key: 'office_location', label: 'Office Location', type: 'text' },
      { key: 'skills', label: 'Skills', type: 'text' },
    ],
  },
  projects: {
    key: 'projects',
    name: 'Projects',
    icon: FiBriefcase,
    color: '#004E8C',
    description: 'Project management and operations',
    columns: [
      { key: 'name', label: 'Project' },
      { key: 'manager', label: 'Manager' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'progress', label: 'Progress', format: 'percent' },
      { key: 'budget', label: 'Budget', format: 'currency' },
    ],
    fields: [
      { key: 'name', label: 'Project Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'manager', label: 'Manager', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Planning', 'In Progress', 'On Hold', 'Completed', 'Cancelled'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'budget', label: 'Budget', type: 'number' },
      { key: 'actual_cost', label: 'Actual Cost', type: 'number' },
      { key: 'progress', label: 'Progress (%)', type: 'number' },
    ],
  },
  tasks: {
    key: 'tasks',
    name: 'Tasks',
    icon: FiCheckSquare,
    color: '#567C73',
    description: 'Task management and tracking',
    columns: [
      { key: 'title', label: 'Task' },
      { key: 'project_name', label: 'Project' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'status', label: 'Status', badge: true },
      { key: 'due_date', label: 'Due Date', format: 'date' },
    ],
    fields: [
      { key: 'title', label: 'Task Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'project_name', label: 'Project', type: 'text' },
      { key: 'assigned_to', label: 'Assigned To', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Not Started', 'In Progress', 'Completed', 'On Hold'] },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'estimated_hours', label: 'Estimated Hours', type: 'number' },
      { key: 'actual_hours', label: 'Actual Hours', type: 'number' },
      { key: 'category', label: 'Category', type: 'select', options: ['Development', 'Design', 'Testing', 'Documentation', 'Planning', 'Security', 'Compliance'] },
    ],
  },
  activities: {
    key: 'activities',
    name: 'Activities',
    icon: FiCalendar,
    color: '#8E562E',
    description: 'Calendar events, calls, and tasks',
    columns: [
      { key: 'type', label: 'Type', badge: true },
      { key: 'subject', label: 'Subject' },
      { key: 'regarding', label: 'Regarding' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'start_date', label: 'Start', format: 'datetime' },
    ],
    fields: [
      { key: 'type', label: 'Type', type: 'select', options: ['Meeting', 'Call', 'Email', 'Task', 'Appointment'], required: true },
      { key: 'subject', label: 'Subject', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'regarding', label: 'Regarding', type: 'text' },
      { key: 'assigned_to', label: 'Assigned To', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Planned', 'In Progress', 'Completed', 'Cancelled'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Normal', 'High', 'Critical'] },
      { key: 'start_date', label: 'Start Date', type: 'datetime-local' },
      { key: 'end_date', label: 'End Date', type: 'datetime-local' },
      { key: 'location', label: 'Location', type: 'text' },
    ],
  },
  territories: {
    key: 'territories',
    name: 'Territories',
    icon: FiMap,
    color: '#2D7D9A',
    description: 'Sales territories and regions',
    columns: [
      { key: 'name', label: 'Territory' },
      { key: 'region', label: 'Region' },
      { key: 'manager', label: 'Manager' },
      { key: 'target_revenue', label: 'Target', format: 'currency' },
      { key: 'actual_revenue', label: 'Actual', format: 'currency' },
      { key: 'account_count', label: 'Accounts' },
    ],
    fields: [
      { key: 'name', label: 'Territory Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'select', options: ['West', 'East', 'Central', 'South', 'Southeast', 'Southwest', 'Northeast', 'National', 'International'] },
      { key: 'manager', label: 'Manager', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'target_revenue', label: 'Target Revenue', type: 'number' },
      { key: 'actual_revenue', label: 'Actual Revenue', type: 'number' },
      { key: 'account_count', label: 'Account Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
    ],
  },
  competitors: {
    key: 'competitors',
    name: 'Competitors',
    icon: FiShield,
    color: '#A4262C',
    description: 'Competitive intelligence and analysis',
    columns: [
      { key: 'name', label: 'Competitor' },
      { key: 'industry', label: 'Industry' },
      { key: 'market_share', label: 'Market Share', format: 'percent' },
      { key: 'threat_level', label: 'Threat', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Competitor Name', type: 'text', required: true },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'strengths', label: 'Strengths', type: 'textarea' },
      { key: 'weaknesses', label: 'Weaknesses', type: 'textarea' },
      { key: 'market_share', label: 'Market Share (%)', type: 'number' },
      { key: 'threat_level', label: 'Threat Level', type: 'select', options: ['High', 'Medium', 'Low'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
    ],
  },
  goals: {
    key: 'goals',
    name: 'Goals',
    icon: FiFlag,
    color: '#986F0B',
    description: 'Business goals and KPIs',
    columns: [
      { key: 'name', label: 'Goal' },
      { key: 'owner', label: 'Owner' },
      { key: 'type', label: 'Type' },
      { key: 'target_value', label: 'Target', format: 'number' },
      { key: 'progress', label: 'Progress', format: 'percent' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Goal Name', type: 'text', required: true },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['Revenue', 'Acquisition', 'CSAT', 'Pipeline', 'HR', 'NPS', 'Leads', 'Operational', 'Community', 'Finance', 'Sales', 'Service'] },
      { key: 'target_value', label: 'Target Value', type: 'number' },
      { key: 'actual_value', label: 'Actual Value', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Not Started', 'In Progress', 'Achieved', 'Missed'] },
      { key: 'progress', label: 'Progress (%)', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },

  // ============ NEW MODULES ============

  departments: {
    key: 'departments',
    name: 'Departments',
    icon: FiLayers,
    color: '#6B69D6',
    description: 'Organizational departments and divisions',
    columns: [
      { key: 'name', label: 'Department' },
      { key: 'code', label: 'Code' },
      { key: 'manager', label: 'Manager' },
      { key: 'employee_count', label: 'Employees' },
      { key: 'budget', label: 'Budget', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Department Name', type: 'text', required: true },
      { key: 'code', label: 'Department Code', type: 'text' },
      { key: 'manager', label: 'Manager', type: 'text' },
      { key: 'parent_department', label: 'Parent Department', type: 'text' },
      { key: 'employee_count', label: 'Employee Count', type: 'number' },
      { key: 'budget', label: 'Budget', type: 'number' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  performance_reviews: {
    key: 'performance_reviews',
    name: 'Performance Reviews',
    icon: FiStar,
    color: '#D4A017',
    description: 'Employee performance evaluations',
    columns: [
      { key: 'employee_name', label: 'Employee' },
      { key: 'reviewer', label: 'Reviewer' },
      { key: 'review_period', label: 'Period' },
      { key: 'overall_rating', label: 'Rating' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'review_date', label: 'Date', format: 'date' },
    ],
    fields: [
      { key: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { key: 'reviewer', label: 'Reviewer', type: 'text', required: true },
      { key: 'review_period', label: 'Review Period', type: 'select', options: ['Q1 2024', 'Q2 2024', 'Q3 2024', 'Q4 2024', 'Annual 2024', 'Q1 2025', 'Q2 2025'] },
      { key: 'overall_rating', label: 'Overall Rating (1-5)', type: 'number' },
      { key: 'goals_rating', label: 'Goals Rating (1-5)', type: 'number' },
      { key: 'skills_rating', label: 'Skills Rating (1-5)', type: 'number' },
      { key: 'communication_rating', label: 'Communication Rating (1-5)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'In Progress', 'Completed', 'Acknowledged'] },
      { key: 'strengths', label: 'Strengths', type: 'textarea' },
      { key: 'improvements', label: 'Areas for Improvement', type: 'textarea' },
      { key: 'comments', label: 'Comments', type: 'textarea' },
      { key: 'review_date', label: 'Review Date', type: 'date' },
    ],
  },
  leave_requests: {
    key: 'leave_requests',
    name: 'Leave Requests',
    icon: FiClock,
    color: '#00897B',
    description: 'Employee leave and time-off requests',
    columns: [
      { key: 'employee_name', label: 'Employee' },
      { key: 'leave_type', label: 'Type' },
      { key: 'start_date', label: 'Start', format: 'date' },
      { key: 'end_date', label: 'End', format: 'date' },
      { key: 'days_requested', label: 'Days' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { key: 'leave_type', label: 'Leave Type', type: 'select', options: ['Annual Leave', 'Sick Leave', 'Personal Leave', 'Maternity Leave', 'Paternity Leave', 'Bereavement', 'Unpaid Leave', 'Work From Home'], required: true },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true },
      { key: 'end_date', label: 'End Date', type: 'date', required: true },
      { key: 'days_requested', label: 'Days Requested', type: 'number' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Approved', 'Rejected', 'Cancelled'] },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  work_orders: {
    key: 'work_orders',
    name: 'Work Orders',
    icon: FiTool,
    color: '#5D4037',
    description: 'Field service work orders and dispatching',
    columns: [
      { key: 'work_order_number', label: 'WO #' },
      { key: 'title', label: 'Title' },
      { key: 'account_name', label: 'Account' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'status', label: 'Status', badge: true },
      { key: 'scheduled_date', label: 'Scheduled', format: 'date' },
    ],
    fields: [
      { key: 'work_order_number', label: 'Work Order #', type: 'text' },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['Installation', 'Repair', 'Maintenance', 'Inspection', 'Upgrade', 'Emergency'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['New', 'Scheduled', 'In Progress', 'Completed', 'Cancelled'] },
      { key: 'assigned_to', label: 'Assigned To', type: 'text' },
      { key: 'scheduled_date', label: 'Scheduled Date', type: 'date' },
      { key: 'completed_date', label: 'Completed Date', type: 'date' },
      { key: 'estimated_hours', label: 'Estimated Hours', type: 'number' },
      { key: 'actual_hours', label: 'Actual Hours', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'resolution', label: 'Resolution', type: 'textarea' },
      { key: 'location', label: 'Location', type: 'text' },
    ],
  },
  sla_policies: {
    key: 'sla_policies',
    name: 'SLA Policies',
    icon: FiActivity,
    color: '#C62828',
    description: 'Service level agreements and policies',
    columns: [
      { key: 'name', label: 'Policy Name' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'response_time_hours', label: 'Response (hrs)' },
      { key: 'resolution_time_hours', label: 'Resolution (hrs)' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Policy Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['Cases', 'Work Orders', 'Incidents', 'Service Requests'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'response_time_hours', label: 'Response Time (hours)', type: 'number', required: true },
      { key: 'resolution_time_hours', label: 'Resolution Time (hours)', type: 'number', required: true },
      { key: 'escalation_time_hours', label: 'Escalation Time (hours)', type: 'number' },
      { key: 'business_hours_only', label: 'Business Hours Only', type: 'select', options: ['true', 'false'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Draft'] },
      { key: 'applicable_to', label: 'Applicable To', type: 'text' },
    ],
  },
  email_templates: {
    key: 'email_templates',
    name: 'Email Templates',
    icon: FiMail,
    color: '#1565C0',
    description: 'Marketing and communication email templates',
    columns: [
      { key: 'name', label: 'Template Name' },
      { key: 'subject', label: 'Subject' },
      { key: 'category', label: 'Category' },
      { key: 'type', label: 'Type' },
      { key: 'usage_count', label: 'Usage' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Template Name', type: 'text', required: true },
      { key: 'subject', label: 'Subject Line', type: 'text', required: true },
      { key: 'body', label: 'Email Body', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['Sales', 'Marketing', 'Support', 'Onboarding', 'Follow-up', 'Newsletter', 'Notification', 'Welcome'] },
      { key: 'type', label: 'Type', type: 'select', options: ['Promotional', 'Transactional', 'Automated', 'Manual'] },
      { key: 'language', label: 'Language', type: 'select', options: ['English', 'Spanish', 'French', 'German', 'Portuguese'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Archived'] },
      { key: 'created_by', label: 'Created By', type: 'text' },
    ],
  },
  expense_reports: {
    key: 'expense_reports',
    name: 'Expense Reports',
    icon: FiCreditCard,
    color: '#AD1457',
    description: 'Employee expense reports and reimbursements',
    columns: [
      { key: 'report_number', label: 'Report #' },
      { key: 'employee_name', label: 'Employee' },
      { key: 'department', label: 'Department' },
      { key: 'total_amount', label: 'Total', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
      { key: 'submitted_date', label: 'Submitted', format: 'date' },
    ],
    fields: [
      { key: 'report_number', label: 'Report Number', type: 'text' },
      { key: 'employee_name', label: 'Employee Name', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'select', options: ['Engineering', 'Sales', 'Marketing', 'Customer Service', 'Finance', 'HR', 'Operations'] },
      { key: 'purpose', label: 'Purpose', type: 'textarea' },
      { key: 'total_amount', label: 'Total Amount', type: 'number', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Submitted', 'Approved', 'Rejected', 'Paid'] },
      { key: 'submitted_date', label: 'Submitted Date', type: 'date' },
      { key: 'approved_by', label: 'Approved By', type: 'text' },
      { key: 'approved_date', label: 'Approved Date', type: 'date' },
      { key: 'category', label: 'Category', type: 'select', options: ['Travel', 'Meals', 'Office Supplies', 'Software', 'Equipment', 'Training', 'Client Entertainment', 'Other'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  payments: {
    key: 'payments',
    name: 'Payments',
    icon: FiDollarSign,
    color: '#2E7D32',
    description: 'Payment records and transactions',
    columns: [
      { key: 'payment_number', label: 'Payment #' },
      { key: 'account_name', label: 'Account' },
      { key: 'amount', label: 'Amount', format: 'currency' },
      { key: 'payment_method', label: 'Method' },
      { key: 'payment_date', label: 'Date', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'payment_number', label: 'Payment Number', type: 'text' },
      { key: 'account_name', label: 'Account', type: 'text', required: true },
      { key: 'invoice_number', label: 'Invoice Number', type: 'text' },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'payment_method', label: 'Payment Method', type: 'select', options: ['Credit Card', 'Wire Transfer', 'ACH', 'Check', 'PayPal', 'Cash'] },
      { key: 'payment_date', label: 'Payment Date', type: 'date' },
      { key: 'reference', label: 'Reference', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Pending', 'Failed', 'Refunded'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  vendors: {
    key: 'vendors',
    name: 'Vendors',
    icon: FiTruck,
    color: '#4527A0',
    description: 'Vendor and supplier management',
    columns: [
      { key: 'name', label: 'Vendor' },
      { key: 'contact_name', label: 'Contact' },
      { key: 'category', label: 'Category' },
      { key: 'rating', label: 'Rating' },
      { key: 'payment_terms', label: 'Terms' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Vendor Name', type: 'text', required: true },
      { key: 'contact_name', label: 'Contact Person', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'website', label: 'Website', type: 'text' },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'country', label: 'Country', type: 'text' },
      { key: 'category', label: 'Category', type: 'select', options: ['Technology', 'Office Supplies', 'Professional Services', 'Marketing', 'Facilities', 'Cloud Services', 'Hardware', 'Staffing'] },
      { key: 'payment_terms', label: 'Payment Terms', type: 'select', options: ['Net 15', 'Net 30', 'Net 45', 'Net 60', 'Due on Receipt'] },
      { key: 'rating', label: 'Rating (1-5)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Pending'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  price_lists: {
    key: 'price_lists',
    name: 'Price Lists',
    icon: FiTag,
    color: '#E65100',
    description: 'Product pricing and price lists',
    columns: [
      { key: 'name', label: 'Price List' },
      { key: 'currency', label: 'Currency' },
      { key: 'type', label: 'Type' },
      { key: 'effective_date', label: 'Effective', format: 'date' },
      { key: 'expiry_date', label: 'Expiry', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Price List Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'currency', label: 'Currency', type: 'select', options: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'] },
      { key: 'effective_date', label: 'Effective Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'discount_percent', label: 'Discount (%)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Draft'] },
      { key: 'type', label: 'Type', type: 'select', options: ['Standard', 'Promotional', 'Partner', 'Enterprise', 'Volume'] },
      { key: 'territory', label: 'Territory', type: 'text' },
    ],
  },
  discounts: {
    key: 'discounts',
    name: 'Discounts',
    icon: FiPercent,
    color: '#F4511E',
    description: 'Discount programs and promotions',
    columns: [
      { key: 'name', label: 'Discount' },
      { key: 'code', label: 'Code' },
      { key: 'type', label: 'Type' },
      { key: 'value', label: 'Value' },
      { key: 'start_date', label: 'Start', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Discount Name', type: 'text', required: true },
      { key: 'code', label: 'Discount Code', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['Percentage', 'Fixed Amount', 'Volume', 'Loyalty', 'Seasonal', 'Bundle'] },
      { key: 'value', label: 'Value', type: 'number', required: true },
      { key: 'min_quantity', label: 'Min Quantity', type: 'number' },
      { key: 'max_quantity', label: 'Max Quantity', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'applicable_to', label: 'Applicable To', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Expired'] },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  audit_logs: {
    key: 'audit_logs',
    name: 'Audit Logs',
    icon: FiEye,
    color: '#37474F',
    description: 'System audit trail and activity logs',
    columns: [
      { key: 'action', label: 'Action' },
      { key: 'entity_type', label: 'Entity' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'user_name', label: 'User' },
      { key: 'ip_address', label: 'IP Address' },
      { key: 'timestamp', label: 'Timestamp', format: 'datetime' },
    ],
    fields: [
      { key: 'action', label: 'Action', type: 'select', options: ['Create', 'Update', 'Delete', 'Login', 'Logout', 'Export', 'Import', 'View'], required: true },
      { key: 'entity_type', label: 'Entity Type', type: 'text' },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'user_name', label: 'User', type: 'text' },
      { key: 'changes', label: 'Changes', type: 'textarea' },
      { key: 'ip_address', label: 'IP Address', type: 'text' },
      { key: 'details', label: 'Details', type: 'textarea' },
    ],
  },
  notifications: {
    key: 'notifications',
    name: 'Notifications',
    icon: FiBell,
    color: '#FF6F00',
    description: 'System notifications and alerts',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type', badge: true },
      { key: 'recipient', label: 'Recipient' },
      { key: 'priority', label: 'Priority', badge: true },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'message', label: 'Message', type: 'textarea', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Info', 'Warning', 'Error', 'Success', 'Reminder', 'System'] },
      { key: 'recipient', label: 'Recipient', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Normal', 'High', 'Urgent'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Unread', 'Read', 'Dismissed'] },
      { key: 'link', label: 'Link', type: 'text' },
    ],
  },
  customer_segments: {
    key: 'customer_segments',
    name: 'Customer Segments',
    icon: FiPieChart,
    color: '#6A1B9A',
    description: 'Customer segmentation and targeting',
    columns: [
      { key: 'name', label: 'Segment' },
      { key: 'type', label: 'Type' },
      { key: 'member_count', label: 'Members' },
      { key: 'created_by', label: 'Created By' },
      { key: 'last_evaluated', label: 'Last Evaluated', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Segment Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'criteria', label: 'Criteria', type: 'textarea' },
      { key: 'member_count', label: 'Member Count', type: 'number' },
      { key: 'type', label: 'Type', type: 'select', options: ['Demographic', 'Behavioral', 'Geographic', 'Firmographic', 'Technographic', 'Value-Based'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Draft'] },
      { key: 'created_by', label: 'Created By', type: 'text' },
      { key: 'last_evaluated', label: 'Last Evaluated', type: 'date' },
    ],
  },
  training_courses: {
    key: 'training_courses',
    name: 'Training Courses',
    icon: FiAward,
    color: '#00695C',
    description: 'Employee training and development programs',
    columns: [
      { key: 'name', label: 'Course' },
      { key: 'category', label: 'Category' },
      { key: 'instructor', label: 'Instructor' },
      { key: 'enrolled', label: 'Enrolled' },
      { key: 'format', label: 'Format' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Course Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'category', label: 'Category', type: 'select', options: ['Technical', 'Leadership', 'Compliance', 'Sales', 'Onboarding', 'Soft Skills', 'Product', 'Safety'] },
      { key: 'instructor', label: 'Instructor', type: 'text' },
      { key: 'duration_hours', label: 'Duration (hours)', type: 'number' },
      { key: 'max_participants', label: 'Max Participants', type: 'number' },
      { key: 'enrolled', label: 'Enrolled', type: 'number' },
      { key: 'completed', label: 'Completed', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'In Progress', 'Completed', 'Cancelled'] },
      { key: 'format', label: 'Format', type: 'select', options: ['In-Person', 'Virtual', 'Hybrid', 'Self-Paced', 'Workshop'] },
    ],
  },
  contracts: {
    key: 'contracts',
    name: 'Contracts',
    icon: FiFileText,
    color: '#283593',
    description: 'Contract management and tracking',
    columns: [
      { key: 'contract_number', label: 'Contract #' },
      { key: 'name', label: 'Contract Name' },
      { key: 'account_name', label: 'Account' },
      { key: 'value', label: 'Value', format: 'currency' },
      { key: 'end_date', label: 'End Date', format: 'date' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'contract_number', label: 'Contract Number', type: 'text' },
      { key: 'name', label: 'Contract Name', type: 'text', required: true },
      { key: 'account_name', label: 'Account', type: 'text' },
      { key: 'contact_name', label: 'Contact', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['Subscription', 'Service', 'License', 'Support', 'Consulting', 'Partnership', 'NDA', 'SLA'] },
      { key: 'value', label: 'Contract Value', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date' },
      { key: 'end_date', label: 'End Date', type: 'date' },
      { key: 'renewal_date', label: 'Renewal Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Active', 'Expired', 'Cancelled', 'Pending Renewal'] },
      { key: 'terms', label: 'Terms', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  forecasts: {
    key: 'forecasts',
    name: 'Forecasts',
    icon: FiBarChart2,
    color: '#0277BD',
    description: 'Sales forecasting and revenue projections',
    columns: [
      { key: 'name', label: 'Forecast' },
      { key: 'period', label: 'Period' },
      { key: 'owner', label: 'Owner' },
      { key: 'target_amount', label: 'Target', format: 'currency' },
      { key: 'committed', label: 'Committed', format: 'currency' },
      { key: 'status', label: 'Status', badge: true },
    ],
    fields: [
      { key: 'name', label: 'Forecast Name', type: 'text', required: true },
      { key: 'period', label: 'Period', type: 'select', options: ['Q1 2024', 'Q2 2024', 'Q3 2024', 'Q4 2024', 'H1 2024', 'H2 2024', 'FY 2024', 'Q1 2025', 'Q2 2025'] },
      { key: 'owner', label: 'Owner', type: 'text' },
      { key: 'target_amount', label: 'Target Amount', type: 'number', required: true },
      { key: 'best_case', label: 'Best Case', type: 'number' },
      { key: 'committed', label: 'Committed', type: 'number' },
      { key: 'pipeline', label: 'Pipeline', type: 'number' },
      { key: 'closed', label: 'Closed', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Open', 'Closed', 'Draft'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
};

export const moduleList = Object.values(modules);

export const sidebarGroups = [
  { label: 'Sales', items: ['contacts', 'accounts', 'leads', 'opportunities', 'quotes', 'orders', 'invoices', 'territories', 'competitors', 'price_lists', 'discounts', 'contracts', 'forecasts'] },
  { label: 'Service', items: ['cases', 'knowledge_articles', 'work_orders', 'sla_policies'] },
  { label: 'Marketing', items: ['campaigns', 'email_templates', 'customer_segments'] },
  { label: 'Finance', items: ['expense_reports', 'payments', 'vendors'] },
  { label: 'Operations', items: ['products', 'projects', 'tasks', 'activities', 'goals'] },
  { label: 'HR', items: ['employees', 'departments', 'performance_reviews', 'leave_requests', 'training_courses'] },
  { label: 'System', items: ['audit_logs', 'notifications'] },
];
